# Generated by Django 4.2.23 on 2025-07-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_season_seasonportfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
