# Generated by Django 4.2.23 on 2025-08-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leagues", "0002_alter_leaguemembership_options_and_more"),
        ("stocks", "0007_transaction_rename_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="is_buy",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="stock",
        ),
        migrations.AddField(
            model_name="transaction",
            name="league",
            field=models.ForeignKey(
                to='leagues.league',
                on_delete=django.db.models.deletion.CASCADE,
                null=True,  # ✅ 추가: 먼저 NULL 허용
                blank=True  # ✅ 추가
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="side",
            field=models.CharField(
                choices=[("BUY", "BUY"), ("SELL", "SELL")], default="", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="symbol",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="average_price",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='league',
            field=models.ForeignKey(
                to='leagues.league',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stock_portfolios',
                null=True,  # ✅ 잠시 NULL 허용
                blank=True,  # ✅
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="shares",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portfolios",
                to="stocks.stock",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="shares",
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.UniqueConstraint(
                fields=("user", "league", "symbol"), name="uniq_user_league_symbol"
            ),
        ),
        migrations.AddField(
            model_name="leaguebalance",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_balances",
                to="leagues.league",
            ),
        ),
        migrations.AddField(
            model_name="leaguebalance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_balances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="leaguebalance",
            constraint=models.UniqueConstraint(
                fields=("user", "league"), name="uniq_user_league_balance"
            ),
        ),
    ]
