# Generated by Django 4.2.23 on 2025-10-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0002_alter_leaguemembership_options_and_more"),
        ("stocks", "0010_alter_league_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="league",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_portfolios",
                to="leagues.league",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="league",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transactions",
                to="leagues.league",
            ),
        ),
    ]
