# Generated by Django 4.2.23 on 2025-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaguemembership",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="leaguemembership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="leaguemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="unique_active_membership_per_user",
            ),
        ),
    ]
